### PR TITLE
Make address copiable to clipboard for MasterCopyItem

### PR DESCRIPTION
**Pull request by elgatovital**
Handles #911 

Changes proposed in this pull request:
- Copy address to clipboard on click
- Disable leak canary

@gnosis/mobile-devs

### CODE REVIEW

**Comment by rmeissner** [comment]
I would love a comment in the PR description on why leak canary was deactivated (even so it was just added yesterday) ;)

**Comment by elgatovital** [comment]
> I would love a comment in the PR description on why leak canary was deactivated (even so it was just added yesterday) ;)

sure. That is something I wanted to discuss. In my understanding memory leak deteftion was a profiling task. Wether it is leak canary or something else is irrelevant. It is fine to use leak canary but I don't want profiler being enabled all the time on all of my devices. We should profile app from time to time though.

**Comment by rmeissner** [comment]
In my opinion this makes sense, and theoretically you could have a separate build type for that, right? (e.g. like profiling and make it a `profilingImplementation` dependency)

**Comment by elgatovital** [comment]
> In my opinion this makes sense, and theoretically you could have a separate build type for that, right? (e.g. like profiling and make it a `profilingImplementation` dependency)

yes, this would be better than having it for dev builds

**Review by rmeissner — APPROVED** [review]

**Pull request merged**
