### PR TITLE
Safe name screen fixes to match design

### PR DESCRIPTION
**Pull request by jpalvarezl**
Changes proposed in this pull request:
- Restored button for terms (casing was not all caps and style was used) 
- Toolbar to look as in the mocks
- NEXT button behaviour implemented

@gnosis/mobile-devs

### CODE REVIEW

**Comment by biafra23** [comment]
The boldness in the address formatting seems bolder in the Zeplin layout. I guess we're using this everywhere?

image

image

**Comment by jpalvarezl** [comment]
Yeah, I am using `TextDark.Bold` like everywhere else.

**Comment by jpalvarezl** [comment]
You can see that change in line 97 in this file: `app/src/main/res/layout/fragment_add_safe_name.xml`

**Comment by biafra23** [comment]
> You can see that change in line 97 in this file: `app/src/main/res/layout/fragment_add_safe_name.xml`

I meant the first byte and the last two bytes of the Ethereum address. Not the text below it.

**Comment by jpalvarezl** [comment]
Nah man you were absolutely right :) the span we used was just switching the colour to black without touching the typeface at all. Now I am also bolding the text :) well spotted.

**Comment by jpalvarezl** [comment]
Looks like this now:
Screenshot_1592224423

**Pull request merged**
