### PR TITLE
Fixing colors and font size for bottom sheet

### PR DESCRIPTION
**Pull request by biafra23**
Handles #1148 

Changes proposed in this pull request:
- Fixing colors and font size according to design https://zpl.io/aMJDlkz

Light | Dark
----- | -----
image | image

Update (fontFamily sans-serif instead sans-serif-medium):
Light | Dark
----- | -----
image | image

@gnosis/mobile-devs

### CODE REVIEW

**Comment by elgatovital** [comment]
text for input items is not bold in the designs
https://zpl.io/aMJDlkz

**Comment by biafra23** [comment]
> text for input items is not bold in the designs
> https://zpl.io/aMJDlkz

AFAICT it is not bold in either TextDark and TextMedium.  Is it really bold in the screenshot?

**Comment by elgatovital** [comment]
fontFamily is sans-serif and not sans-serif-medium

**Review by jpalvarezl — APPROVED** [review]
Looks good to me. It doesn't seem to be bolded in the mocks to me either. Also, the mocks show it as ` android:textStyle="normal"`

**Comment by biafra23** [comment]
@elgatovital Font family fixed in latest commit. 7219b80d5b81b91fce594c1d3e01b1737ad25f1e

**Review by elgatovital — APPROVED** [review]

**Pull request merged**
