### PR TITLE
Prevent opening Terms Sheet if already added

### PR DESCRIPTION
**Pull request by biafra23**
Handles #970

Changes proposed in this pull request:
- Prevents opening the Terms Sheet if it is already added
- Also does not re-open it (when it was dismissed) when coming back from background, because the last event is HideTerms in that case.

@gnosis/mobile-devs

### CODE REVIEW

**Review by jpalvarezl — APPROVED** [review]
I would give this a try using the `SplashViewModel` inheriting from a `PublishViewModel` but if that doesn't do the trick, let's keep the proposed solution in this PR.

I will approve nonetheless so that you can merge at your earliest convenience.

**Review by elgatovital — CHANGES_REQUESTED** [review]
what about handling the case when user clicks "no thanks", dismisses bottom sheet, and then navigates away from the app

**Comment by jpalvarezl** [comment]
I am not sure where in the epic the expected behaviour is specified, but I think we are supposed to pester the users until we get an `Accept` 😆  not sure though.

**Review by elgatovital — APPROVED** [review]

**Comment by elgatovital** [comment]
In case the user dismisses the dialog and navigates away it would be more intuitive to return to the page with the same state as it was before leaving the app: dialog dismissed and get started button is shown. So user has to click it to see the dialog again. In the current implementation user will return to the page with the dialog being dispayed already @jpalvarezl @biafra23

**Review by elgatovital — APPROVED** [review]

**Comment by elgatovital** [comment]
lgtm 👍

**Pull request merged**
